### ISSUE TITLE
[AL2023-minimal] java-17-amazon-corretto-headless-1:17.0.10+7-1.amz

### ISSUE THREAD

**Issue by Luis-3M** [amazonlinux/container-images#103]
### Product

Amazon Linux 2023

### Package

java-17-amazon-corretto-headless-1:17.0.10+7-1.amz

### Why do you need this package?

As per Amazon Linux 2023 Security Advisory `ALAS-2024-483` we need to get `java-17-amazon-corretto-headless` version `17.0.10` installed in our systems.

We're not able to install it using the latest `2023-minimal` image.

`docker run -it public.ecr.aws/amazonlinux/amazonlinux:2023-minimal`

`bash-5.2# dnf install -y java-17-amazon-corretto-headless --releasever 2023.3.20240117`
`bash-5.2# java --version`
`openjdk 17.0.9 2023-10-17 LTS`
`OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS)`
`OpenJDK 64-Bit Server VM Corretto-17.0.9.8.1 (build 17.0.9+8-LTS, mixed mode, sharing)`

Sources: https://alas.aws.amazon.com/AL2023/ALAS-2024-483.html

**Comment by Timidger** [comment]
Hi there! I was able to reproduce your issue by booting up an older AMI without the updated JDK, downloading the older version, then attempting to install the newer version with the command you specified.

However, I think the issue is that the wrong command is being provided. [The ALAS page associated with this issue](https://alas.aws.amazon.com/AL2023/ALAS-2024-483.html) provides this command for remediating older instances:

```
dnf update java-17-amazon-corretto --releasever 2023.3.20240117
```

Note `update` and not `install`. Try running the command again but replace `install` with `update`.

Let me know if this doesn't resolve your issue, or if there's something I missed during my reproduction steps.

**Comment by Luis-3M** [comment]
Hi @Timidger,
AWS has just released a new version of both `AL2023` and `AL2023-minimal` images, so we've just moved forward.
Interesting that the previous command could not be executed on containers using `AL2023-minimal`, but we could do it on containers using `AL2023`.

Nonetheless, this issue is no longer valid and will close it now.
