### ISSUE TITLE
minimal images

### ISSUE THREAD

**Issue by sacreman** [amazonlinux/container-images#15]
Is there any plan to support minimal images? The current Amazon Linux 2 image is 163mb on disk and contains quite a few packages that probably aren't required. This presents an unnecessary surface area for security vulnerabilities.

Project Atomic have released Buildah which can create extremely small Centos base images.

[This blog](https://www.informaticsmatters.com/blog/2018/05/31/smaller-containers-part-3.html) describes how to strip all packages out except bash and coreutils.

It would be great if Amazon Linux was made available with a minimal tag. Or, if somebody could provide some info on how to build a minimal image themselves.

**Comment by ilianaw** [comment]
Our images are already as minimal as we can reasonably make it without major (breaking!) changes. For instance, the `amazonlinux:2` (`latest`) image only deliberately has these packages installed:

* amazon-linux-extras
* basesystem
* bash
* ca-certificates
* coreutils
* glibc-langpack-en
* glibc-minimal-langpack
* system-release
* vim-minimal
* yum
* yum-plugin-ovl (required for things to work right on overlay)
* yum-plugin-priorities

We can't ship you a container without yum, because then you can't use it. Every single other package here is in service of yum, or doesn't significantly increase the footprint (amazon-linux-extras entirely uses the Python standard library which you're going to have anyway with yum, for instance). The goal of the official images program that we participate in is to ship base images reasonable for most users.

I think that if we can get Buildah or another project to work with Amazon Linux we should document that, and if that interests you we'll accept a pull request to the README here if you get to it before we can. :)

**Comment by ilianaw** [comment]
microdnf seems promising then, especially if RHEL is doing it (our versions of yum are very close). We'll take a look. Being able to drop Python would give us a pretty good slim image. (I think we'd need a micro amazon-linux-extras CLI then but that doesn't seem like that bad of a problem.)

**Comment by Sodki** [comment]
microdnf _seems_ like a good solution, but in real world scenarios you'll end up installing some packages and it becomes almost as large as regular images. Of course your mileage may vary.

**Comment by alanwilter** [comment]
I'm giving a try on `amazonlinux` latest from Docker Hub and I'm appalled with this "minimum", `yum list installed` shows me 105 packages, including `python2`! Really?

**Comment by alanwilter** [comment]
If `amazonlinux` could at least replace python2 for python3 (I must do it eventually) in one of its Docker image, that would help a lot.

**Comment by iliana** [comment]
@alanwilter yum is Python 2 only.

> We can't ship you a container without yum, because then you can't use it. Every single other package here is in service of yum, or doesn't significantly increase the footprint (amazon-linux-extras entirely uses the Python standard library which you're going to have anyway with yum, for instance). The goal of the official images program that we participate in is to ship base images reasonable for most users.

As this thread discusses, dnf or microdnf would be a possible path toward a more minimal container image. We're evaluating options for supporting this in AL2, but I can't speak to any commitments.

You can also use multi-stage builds to build your own minimal base images if you don't need yum by using `yum --installroot` and a second stage that copies from that path.

**Comment by alanwilter** [comment]
Well, `yum` will have to move or be dropped. Python 2 stopped development since 1st Jan 2020!

**Comment by jcranfordupgrade** [comment]
Please consider re-opening this issue. It would be really helpful if the Amazon Linux base image was split into layers.

An example with two layers could be:
1. No Extras Image = Scratch + Minimal Tar Ball
2. Extras Image = No Extras Image + [Extras mentioned in this previous comment](https://github.com/amazonlinux/container-images/issues/15#issuecomment-430826177)

I deal with a few use cases of running containers in AWS EKS, where yum + extras are:
1. needed at deploy time & runtime (e.g. do installs & updates)
2. needed at deploy time only, **not at runtime** (e.g. one-time jobs)
3. **not needed at all** (e.g. static executable on Busybox)

For use case 3, I recently tried moving a Golang static executable from Amazon Linux to Busybox. Image sizes were:
- Amazon Linux 2: 233MB
- Amazon Linux 2023: 200MB
- Alpine: 27MB
- Busybox: 24MB

However, I am constrained to use Amazon base images, and no sub-layers are visible. The [multi-stage Dockerfile](https://github.com/amazonlinux/container-images/blob/e2a12edeb2149ac97b854b43676c4117ced6fb70/Dockerfile#L4) appears to bootstrap on Alpine, download and extract a tar file, and copy it to / in a release image built from stratch. That effectively squashes any intermediate layers used to build the base image. It would be great to expose at least one sub-layer of that base image, without yum + extras.

To get an idea of the space taken up by extras, I downloaded the [al2023-container-2023.1.20230705.0-x86_64.tar.xz](https://amazon-linux-docker-sources.s3.amazonaws.com/al2023/2023.1.20230705.0/al2023-container-2023.1.20230705.0-x86_64.tar.xz) tarball referenced in the latest Dockerfile at the time I am writing this response. I see a lot of extras that don't apply to a static Go executable (or other types of executables).

```
wget https://amazon-linux-docker-sources.s3.amazonaws.com/al2023/2023.1.20230705.0/al2023-container-2023.1.20230705.0-x86_64.tar.xz
mkdir /tmp/amazonlinux3-rootfs
tar -C /tmp/amazonlinux3-rootfs --extract --file al2023-container-2023.1.20230705.0-x86_64.tar.xz
pushd /tmp/amazonlinux3-rootfs
du -sh ./* | sort -h
du -sh ./usr/* | sort -h
du -sh ./usr/share/* | sort -h
du -sh ./usr/lib64/* | sort -h
```

Sampled size from running a few of the above `du -sh *` exploratory commands:
```
22M of locale data
7.5M of misc magic
4.3M of zoneinfo
3.8M of doc
```

**Comment by mysteriouspants** [comment]
As I recall static Go binaries do not have a libc/glibc dependency, so you should be able to use `FROM scratch` instead of any specific base image.

We build Amazon Linux from packages by bootstrapping a package manager in a chroot and then installing a minimal set of software. We consider the existing containers to be "minimal," though it would seem that more shaving can be done. I can't alter the way we currently delivery Amazon Linux containers because that could break other customer environments. I will, however, ask our core engineering team to evaluate creating a "minimal this time for real" container, because I agree that 200Mb is pretty big for what a container should be.

Reopening ticket while the internal question is still open.

**Comment by nmeyerhans** [comment]
In Debian we have the regular images, and a "-slim" variant that further reduces the footprint:
```
$ docker inspect public.ecr.aws/debian/debian:bullseye --format '{{.Size}}'     
124119398
$ docker inspect public.ecr.aws/debian/debian:bullseye-slim --format '{{.Size}}'
80514853
```

The package list itself in the -slim variant is actually identical to the regular images, but the is additional [dpkg configuration](https://github.com/debuerreotype/debuerreotype/blob/master/scripts/debuerreotype-slimify) to exclude certain files from the slim variants.  It's not clear whether something similar can be done with rpm/dnf in Amazon Linux, but it's something that should be looked at.

**Comment by stewartsmith** [comment]
For creating a minimal container for the following `hello-world.go`:
```
package main

import "fmt"

func main() {
    fmt.Println("hello world")
}
```

You can use the `--installroot` functionality of `dnf` along with `FROM scratch` to create the absolute bare minimum needed to run the produced binary.

Below is the `Dockerfile` that does so:

```
FROM public.ecr.aws/amazonlinux/amazonlinux:2023 as build
COPY hello-world.go /
RUN dnf -y install golang
RUN go build hello-world.go
RUN mkdir /sysroot
RUN mv hello-world /sysroot
RUN echo dnf --releasever=$(rpm -q system-release --qf '%{VERSION}') \
  --installroot /sysroot \
  -y \
  --setopt=install_weak_deps=False \
  install bash

FROM scratch
COPY --from=build /sysroot /
WORKDIR /
ENTRYPOINT ["/hello-world"]
```

The same can also be done for `hello-world.c`:
```
#include <stdio.h>
int main(void) { printf("Hello World!\n"); return 0; }
```

with the following `Dockerfile`:
```
FROM public.ecr.aws/amazonlinux/amazonlinux:2023 as build
COPY hello-world.c /
RUN dnf -y install gcc
RUN gcc -o hello-world hello-world.c
RUN mkdir /sysroot
RUN mv hello-world /sysroot/
RUN dnf --releasever=$(rpm -q system-release --qf '%{VERSION}') \
  --installroot /sysroot \
  -y \
  --setopt=install_weak_deps=False \
  install glibc && dnf --installroot /sysroot clean all

FROM scratch
COPY --from=build /sysroot /
WORKDIR /
ENTRYPOINT ["/hello-world"]
```

For the C example, if I compress the produced container image with `zstd`, it's 5.4MB (and 26MB as a straight `tar`).

Having examples like this in the documentation for Amazon Linux is likely worthwhile, as even with `microdnf` in AL2023, you may still want to construct minimal layers that do not have a package manager.

**Comment by stewartsmith** [comment]
Check out https://docs.aws.amazon.com/linux/al2023/ug/minimal-container.html for documentation on a (significantly) smaller AL2023 container image with `microdnf` rather than `dnf` (and thus avoids Python and a few other dependencies), and https://docs.aws.amazon.com/linux/al2023/ug/barebones-containers.html which covers the above bare bones approach.

With the availability of the minimal image, I think we can probably close this issue now?
