### ISSUE TITLE
tar: command not found on amazonlinux:2-with-sources

### ISSUE THREAD

**Issue by sawanoboly** [amazonlinux/container-images#29]
Hi,
When I tried to use the tar command with the `amazonlinux: 2-with-sources` image, it was not installed.

```
$ docker run -it --rm amazonlinux:2-with-sources bash -c 'tar --version'
bash: tar: command not found
```

It looks like it's installed when you look at the source, but why is it not found?

https://github.com/amazonlinux/container-images/blob/master/update-script/update.sh#L164

The purpose of use is file sharing between builds on the CircleCI service.  It does not work because they expect the image to contain the tar utility.

Here is an example of the result.

> tar utility is not present in this image but it is required. Please install it to have workflow workspace capability.
> https://circleci.com/gh/OpsRockin/nginx_preview_for_amimoto/153#usage-queue/containers/0

**Comment by iliana** [comment]
> It looks like it's installed when you look at the source, but why is it not found?
> 
> https://github.com/amazonlinux/container-images/blob/master/update-script/update.sh#L164

This is the script used to generate the commits to this git repo, not the tool used to generate the image. tar is not installed in the container image because the container image is as minimal as possible.

```
yum install -y tar
```

Are you sure you need the `with-sources` version of the image? It is much larger and just happens to provide a tarball of the source RPMs distributed with the image.

**Comment by sawanoboly** [comment]
hmm... I think that it's kind of awkward to create a custom image just for tar...
