### ISSUE TITLE
Update to 19.03

### ISSUE THREAD

**Issue by daveisfera** [amazonlinux/container-images#35]
19.03 has been out for several months now and has improved support for `buildkit` (which is being pushed as the preferred method for building docker images going forward), so can it be made available?

**Comment by jhaynes** [comment]
Hi @daveisfera 

This isn't the best place for questions/asks like this since this repo is specific to Amazon Linux container images. Instead AWS support, AWS Forums, or one of our other feedback mechanisms is a better fit.

That said, we absolutely have Docker 19.03 (hopefully .6) on our radar and share your excitement about the `buildkit` support!

**Comment by daveisfera** [comment]
Sorry, was just going off of #24 and is there somewhere to track the progress of this update because we've started playing around with `buildkit` and we're running into issues with 18.09 that we believe will be resolved by 19.03

**Comment by jhaynes** [comment]
No worries, and these github issues _do_ get attention of the right people. But ideally we keep this particular repo specific to the Amazon Linux container images :)  

We don't have things like Docker update timelines on a public roadmap currently, but it is something we're open to exploring. We use customer feedback on Docker features and bug fixes as one of the big drivers for releasing new versions, so we definitely appreciate the input!
