### ISSUE TITLE
Cannot start service awslogsd when build image with awslogs from amazonlinux  

### ISSUE THREAD

**Issue by virutmath** [amazonlinux/container-images#39]
My Dockerfile
FROM amazonlinux:latest

RUN yum install -y awslogs
COPY ./awscli.conf /etc/awslogs/awscli.conf
COPY ./awslogs.conf /etc/awslogs/awslogs.conf
RUN service awslogs start
RUN systemctl start awslogsd

CMD ["/bin/bash"]

But when I build, I received error:
```Redirecting to /bin/systemctl start awslogs.service
Failed to get D-Bus connection: Operation not permitted
```
If I comment `RUN service awslogs start`, then build and run docker image with param `-d --privileged` and start service manual => everthing OK

**Comment by jhaynes** [comment]
Hi @virutmath 

If I use your example `Dockerfile` I also get an error from the `systemctl start awslogsd` line in addition to the `service awslogs start` line and they're related. The `service` command is available in `systemd` based OSes for backward compat (and comfort), but just invokes the `systemctl` command under the covers. 

The error you're seeing is because systemd (or any init system) isn't running during the container build. Instead, you can use `RUN systemctl enable awslogsd` in your `Dockerfile`. However, that won't have any effect unless you start systemd when you create a container: `docker run -d --privileged <my-awslogs-image> /usr/sbin/init`.

All that said, I'm curious why you're looking to run awslogs in a container instead of using [Docker's native logdrivers](https://docs.docker.com/config/containers/logging/configure/) (https://docs.docker.com/config/containers/logging/configure/) to ship container logs. There might be another option to accomplish what you're looking to do with the awslogs daemon inside the container.

**Comment by jhaynes** [comment]
We haven't heard back from you in awhile, so hopefully this issue is resolved. If not, feel free to re-open or create a new issue.
