### ISSUE TITLE
CVE-2021-21285 and CVE-2021-21284

### ISSUE THREAD

**Issue by hi-artem** [amazonlinux/container-images#49]
I am not sure if this is correct place for this issue, but docker 19.03.13, recommended by AWS, is vulnerable to CVE-2021-21285 and CVE-2021-21284. 

There is a separate topic of upgrading to 20.10, which I think should be tracked by #43

**Comment by samuelkarp** [comment]
Hi @hi-artem,

This GitHub repository is used only for the Amazon Linux container images published to Docker Hub and Amazon ECR and isn’t monitored as a general support forum for Amazon Linux.  If you have concerns related to security, we ask that you notify AWS Security via our [vulnerability reporting page](http://aws.amazon.com/security/vulnerability-reporting/) or directly via email to aws-security@amazon.com rather than opening a public GitHub issue.

The latest available version of Docker for Amazon Linux 2 is 20.10.4; you can find `docker-20.10.4-1.amzn2` in the `docker` [extra](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-install-extras-library-software/).  Amazon Linux 1 [ended its standard support on December 31, 2020](https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/) and is only receiving critical and important security updates for a reduced set of packages.  A detailed list of supported and unsupported packages along with additional information is available [here](https://amazonlinux.github.io/al1-support-statements/).

If you have any further security-related concerns, please do not hesitate to reach out to AWS Security through the contact methods listed above.  I will be closing and locking this issue at this time.

Thanks,
Sam
