### ISSUE TITLE
[Security]: CVE-2023-35945⁠ libnghttp2

### ISSUE THREAD

**Issue by johnbrandborg** [amazonlinux/container-images#98]
### Product

Amazon Linux 2

### What is your question?

The [AWS CLI Container](https://hub.docker.com/r/amazon/aws-cli) is built using Amazon Linux 2, as seen in the [Dockerfile](https://github.com/aws/aws-cli/blob/v2/docker/Dockerfile).

The image currently has the vulnerability CVE-2023-35945⁠, seen on the latest release of Amazon Linux 2 with the layer digest of [sha256:9a22f5fa3afedf5058d219d2f06a0f9aba430bcffd44673351f13fb4a6c2f8ca](https://hub.docker.com/layers/library/amazonlinux/2/images/sha256-9a22f5fa3afedf5058d219d2f06a0f9aba430bcffd44673351f13fb4a6c2f8ca?context=repo&tab=vulnerabilities).

Is it possible to update the Amazon CLI Container so it's using a base image without this vulnerability?

**Comment by dadetayo** [comment]
Hello, this CVE has been fixed in our recent Amazon Linux 2 release. You can find details about the CVE [here](https://alas.aws.amazon.com/cve/html/CVE-2023-35945.html). It seems like the AWS cli container has not been updated with our latest AL2 base container yet. You can reach out to the AWS cli team by creating an issue [here](https://github.com/aws/aws-cli/issues). Most likely, they have a fixed release cadence and the new version should be available soon.

**Comment by johnbrandborg** [comment]
Hello @dadetayo, thanks for the reply.  Apologies but I am confused, the container that has the vulnerabilities was release only 13 days ago, and that is the latest.   I don't see a Amazon Linux 2 released on Dockerhub that is clear of this CVE.  Is there another release you take about yet to come?

I will check to see what the AWS CLI Team to find out if they are looking to fix this as you have suggested.

**Comment by johnbrandborg** [comment]
Looks like the vulnerability has been fixed by the AWS CLI Team.  Thanks @dadetayo
